In [1]:
!pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.3-cp38-cp38-win_amd64.whl (1.1 MB)
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.3

In [2]:
import pandas as pd
import psycopg2 as pg2

In [3]:
conn = pg2.connect(host='localhost', port=5432, dbname='demo', user='postgres', password='palmeiras1914')

In [4]:
cur = conn.cursor()

In [5]:
cur.execute('select * from ticket_flights')

In [6]:
conn.commit()

In [7]:
data = cur.fetchall()

In [8]:
cur.close()
conn.close()

In [9]:
data

[('0005432159776', 30625, 'Business', Decimal('42100.00')),
 ('0005435212351', 30625, 'Business', Decimal('42100.00')),
 ('0005435212386', 30625, 'Business', Decimal('42100.00')),
 ('0005435212381', 30625, 'Business', Decimal('42100.00')),
 ('0005432211370', 30625, 'Business', Decimal('42100.00')),
 ('0005435212357', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212360', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212393', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212374', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212365', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212378', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212362', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212334', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212329', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212370', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212328', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435725513', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435630915', 30625, 'Comfort', Decimal('23900.00')),
 ('0005435212388', 30625, 'Economy', Decimal('14000.00')),
 ('0005432159775', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212382', 30625, 'Economy', Decimal('14000.00')),
 ('0005432211367', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212354', 30625, 'Economy', Decimal('14000.00')),
 ('0005432211372', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212344', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212372', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212355', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212376', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212385', 30625, 'Economy', Decimal('15400.00')),
 ('0005435725512', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212336', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212367', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212359', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212364', 30625, 'Economy', Decimal('14000.00')),
 ('0005435725514', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212391', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212338', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212366', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212347', 30625, 'Economy', Decimal('14000.00')),
 ('0005432211366', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212373', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212383', 30625, 'Economy', Decimal('14000.00')),
 ('0005433656614', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212395', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212343', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212371', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212377', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212330', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212358', 30625, 'Economy', Decimal('14000.00')),
 ('0005432211371', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212368', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212335', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212340', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212363', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212380', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212345', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212375', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212350', 30625, 'Economy', Decimal('14000.00')),
 ('0005432211365', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212331', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212353', 30625, 'Economy', Decimal('14000.00')),
 ('0005435630916', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212337', 30625, 'Economy', Decimal('14000.00')),
 ('0005432211368', 30625, 'Economy', Decimal('14000.00')),
 ('0005432211369', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212356', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212332', 30625, 'Economy', Decimal('15400.00')),
 ('0005435212348', 30625, 'Economy', Decimal('15400.00')),
 ('0005435212352', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212394', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212389', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212392', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212369', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212379', 30625, 'Economy', Decimal('14000.00')),
 ('0005435725516', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212396', 30625, 'Economy', Decimal('14000.00')),
 ('0005432159777', 30625, 'Economy', Decimal('14000.00')),
 ('0005433656613', 30625, 'Economy', Decimal('14000.00')),
 ('0005435725515', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212346', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212390', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212361', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212341', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212349', 30625, 'Economy', Decimal('14000.00')),
 ('0005435725511', 30625, 'Economy', Decimal('14000.00')),
 ('0005432159778', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212384', 30625, 'Economy', Decimal('14000.00')),
 ('0005435630914', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212339', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212333', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212387', 30625, 'Economy', Decimal('14000.00')),
 ('0005435212342', 30625, 'Economy', Decimal('14000.00')),
 ('0005433367244', 24836, 'Business', Decimal('9800.00')),
 ('0005433367229', 24836, 'Business', Decimal('9800.00')),
 ('0005433367230', 24836, 'Business', Decimal('9800.00')),
 ('0005433367245', 24836, 'Business', Decimal('9800.00')),
 ('0005433367256', 24836, 'Business', Decimal('9800.00')),
 ('0005433367225', 24836, 'Business', Decimal('9800.00')),
 ('0005433367228', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367236', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367252', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367243', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367222', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367234', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367231', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367218', 24836, 'Economy', Decimal('3600.00')),
 ('0005433367224', 24836, 'Economy', Decimal('3600.00')),
 ('0005433367237', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367255', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367246', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367227', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367233', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367242', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367248', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367223', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367241', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367221', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367258', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367240', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367226', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367247', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367235', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367257', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367251', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367239', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367220', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367250', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367219', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367253', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367232', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367249', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367238', 24836, 'Economy', Decimal('3300.00')),
 ('0005433367254', 24836, 'Economy', Decimal('3300.00')),
 ('0005434979262', 2055, 'Economy', Decimal('10500.00')),
 ('0005434979271', 2055, 'Economy', Decimal('10500.00')),
 ('0005434979277', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979252', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979282', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979273', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979280', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979255', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979269', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979275', 2055, 'Economy', Decimal('9500.00')),
 ('0005435801642', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979279', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979267', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979254', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979264', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979263', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979276', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979270', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979258', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979256', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979265', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979261', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979253', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979259', 2055, 'Economy', Decimal('9500.00')),
 ('0005435801643', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979272', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979260', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979274', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979268', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979257', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979278', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979266', 2055, 'Economy', Decimal('9500.00')),
 ('0005435801644', 2055, 'Economy', Decimal('9500.00')),
 ('0005434979281', 2055, 'Economy', Decimal('9500.00')),
 ('0005434952466', 2575, 'Economy', Decimal('5300.00')),
 ('0005434952464', 2575, 'Economy', Decimal('5300.00')),
 ('0005434952465', 2575, 'Economy', Decimal('5300.00')),
 ('0005434952467', 2575, 'Economy', Decimal('5300.00')),
 ('0005433256382', 28205, 'Economy', Decimal('5300.00')),
 ('0005433256381', 28205, 'Economy', Decimal('5300.00')),
 ('0005433111467', 19732, 'Economy', Decimal('8700.00')),
 ('0005433111468', 19732, 'Economy', Decimal('8700.00')),
 ('0005433112350', 19732, 'Economy', Decimal('8700.00')),
 ('0005433111469', 19732, 'Economy', Decimal('8700.00')),
 ('0005434190367', 19092, 'Economy', Decimal('26000.00')),
 ('0005434190368', 19092, 'Economy', Decimal('23600.00')),
 ('0005433534460', 6786, 'Economy', Decimal('10900.00')),
 ('0005433534461', 6786, 'Economy', Decimal('9900.00')),
 ('0005433534463', 6786, 'Economy', Decimal('9900.00')),
 ('0005433538721', 6786, 'Economy', Decimal('9900.00')),
 ('0005433538717', 6786, 'Economy', Decimal('9900.00')),
 ('0005433538718', 6786, 'Economy', Decimal('9900.00')),
 ('0005433534462', 6786, 'Economy', Decimal('9900.00')),
 ('0005433538720', 6786, 'Economy', Decimal('9900.00')),
 ('0005433538719', 6786, 'Economy', Decimal('9900.00')),
 ('0005433538722', 6786, 'Economy', Decimal('9900.00')),
 ('0005433538723', 6786, 'Economy', Decimal('9900.00')),
 ('0005433538724', 6786, 'Economy', Decimal('9900.00')),
 ('0005435259680', 25029, 'Economy', Decimal('9900.00')),
 ('0005435259678', 25029, 'Economy', Decimal('9900.00')),
 ('0005435259681', 25029, 'Economy', Decimal('9900.00')),
 ('0005435259679', 25029, 'Economy', Decimal('9900.00')),
 ('0005433511804', 823, 'Economy', Decimal('16100.00')),
 ('0005433511803', 823, 'Economy', Decimal('14600.00')),
 ('0005433511809', 823, 'Economy', Decimal('14600.00')),
 ('0005433511807', 823, 'Economy', Decimal('14600.00')),
 ('0005433511802', 823, 'Economy', Decimal('14600.00')),
 ('0005433511801', 823, 'Economy', Decimal('14600.00')),
 ('0005433511808', 823, 'Economy', Decimal('14600.00')),
 ('0005433511806', 823, 'Economy', Decimal('14600.00')),
 ('0005433511805', 823, 'Economy', Decimal('14600.00')),
 ('0005432922454', 16157, 'Economy', Decimal('16100.00')),
 ('0005432922455', 16157, 'Economy', Decimal('14600.00')),
 ('0005432922453', 16157, 'Economy', Decimal('14600.00')),
 ('0005433475633', 4021, 'Economy', Decimal('13500.00')),
 ('0005433475632', 4021, 'Economy', Decimal('12300.00')),
 ('0005433475631', 4021, 'Economy', Decimal('12300.00')),
 ('0005433475630', 4021, 'Economy', Decimal('12300.00')),
 ('0005435696849', 3660, 'Economy', Decimal('7900.00')),
 ('0005435696846', 3660, 'Economy', Decimal('7900.00')),
 ('0005434950451', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696864', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696862', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696847', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696850', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696866', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696843', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696863', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696851', 3660, 'Economy', Decimal('7200.00')),
 ('0005434950450', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696870', 3660, 'Economy', Decimal('7200.00')),
 ('0005434950452', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696859', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696871', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696855', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696869', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696852', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696857', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696853', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696845', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696844', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696856', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696858', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696865', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696848', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696861', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696860', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696854', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696867', 3660, 'Economy', Decimal('7200.00')),
 ('0005435696868', 3660, 'Economy', Decimal('7200.00')),
 ('0005435916119', 16272, 'Economy', Decimal('7200.00')),
 ('0005435916118', 16272, 'Economy', Decimal('7200.00')),
 ('0005432609659', 3993, 'Economy', Decimal('21300.00')),
 ('0005432609661', 3993, 'Economy', Decimal('21300.00')),
 ('0005432607495', 3993, 'Economy', Decimal('21300.00')),
 ('0005434606760', 3993, 'Economy', Decimal('21300.00')),
 ('0005432609658', 3993, 'Economy', Decimal('19300.00')),
 ('0005434606759', 3993, 'Economy', Decimal('19300.00')),
 ('0005434606763', 3993, 'Economy', Decimal('19300.00')),
 ('0005433519378', 3993, 'Economy', Decimal('19300.00')),
 ('0005432607494', 3993, 'Economy', Decimal('19300.00')),
 ('0005433519379', 3993, 'Economy', Decimal('19300.00')),
 ('0005434604838', 3993, 'Economy', Decimal('19300.00')),
 ('0005434606761', 3993, 'Economy', Decimal('19300.00')),
 ('0005433519377', 3993, 'Economy', Decimal('19300.00')),
 ('0005432609660', 3993, 'Economy', Decimal('19300.00')),
 ('0005434604839', 3993, 'Economy', Decimal('19300.00')),
 ('0005434606762', 3993, 'Economy', Decimal('19300.00')),
 ('0005433519380', 3993, 'Economy', Decimal('19300.00')),
 ('0005432607496', 3993, 'Economy', Decimal('19300.00')),
 ('0005434604837', 3993, 'Economy', Decimal('19300.00')),
 ('0005435853578', 22080, 'Economy', Decimal('21300.00')),
 ('0005435853580', 22080, 'Economy', Decimal('19300.00')),
 ('0005435853579', 22080, 'Economy', Decimal('19300.00')),
 ('0005435628670', 728, 'Economy', Decimal('3700.00')),
 ('0005435628672', 728, 'Economy', Decimal('3700.00')),
 ('0005435628669', 728, 'Economy', Decimal('3700.00')),
 ('0005435628671', 728, 'Economy', Decimal('3700.00')),
 ('0005433348889', 15900, 'Economy', Decimal('3700.00')),
 ('0005433348891', 15900, 'Economy', Decimal('3700.00')),
 ('0005433348887', 15900, 'Economy', Decimal('3700.00')),
 ('0005433348888', 15900, 'Economy', Decimal('3700.00')),
 ('0005433348890', 15900, 'Economy', Decimal('3700.00')),
 ('0005433159275', 17677, 'Economy', Decimal('7100.00')),
 ('0005433159274', 17677, 'Economy', Decimal('7100.00')),
 ('0005433159276', 17677, 'Economy', Decimal('7100.00')),
 ('0005435132700', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132696', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132694', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132695', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132698', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132697', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132699', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132703', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132704', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132702', 7862, 'Economy', Decimal('5400.00')),
 ('0005435132701', 7862, 'Economy', Decimal('5400.00')),
 ('0005435383058', 33092, 'Economy', Decimal('5900.00')),
 ('0005435383057', 33092, 'Economy', Decimal('5400.00')),
 ('0005435383056', 33092, 'Economy', Decimal('5400.00')),
 ('0005435383059', 33092, 'Economy', Decimal('5400.00')),
 ('0005435383055', 33092, 'Economy', Decimal('5400.00')),
 ('0005435160112', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160111', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160106', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160104', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160109', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160103', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160105', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160110', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160113', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160107', 7477, 'Economy', Decimal('12500.00')),
 ('0005435160108', 7477, 'Economy', Decimal('12500.00')),
 ('0005435390116', 29573, 'Economy', Decimal('13800.00')),
 ('0005435390120', 29573, 'Economy', Decimal('12500.00')),
 ('0005435390121', 29573, 'Economy', Decimal('12500.00')),
 ('0005435390122', 29573, 'Economy', Decimal('12500.00')),
 ('0005435390118', 29573, 'Economy', Decimal('12500.00')),
 ('0005435390117', 29573, 'Economy', Decimal('12500.00')),
 ('0005435390119', 29573, 'Economy', Decimal('12500.00')),
 ('0005434503467', 6547, 'Business', Decimal('48400.00')),
 ('0005434503492', 6547, 'Business', Decimal('48400.00')),
 ('0005434503487', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503465', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503495', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503472', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503463', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503469', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503460', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503488', 6547, 'Economy', Decimal('17800.00')),
 ('0005434503484', 6547, 'Economy', Decimal('17800.00')),
 ('0005434503490', 6547, 'Economy', Decimal('17800.00')),
 ('0005434503468', 6547, 'Economy', Decimal('17800.00')),
 ('0005434503482', 6547, 'Economy', Decimal('16100.00')),
 ('0005435103797', 6547, 'Economy', Decimal('16100.00')),
 ('0005435103796', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503479', 6547, 'Economy', Decimal('16100.00')),
 ('0005435103802', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503471', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503494', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503483', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503474', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503464', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503476', 6547, 'Economy', Decimal('16100.00')),
 ('0005435103803', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503462', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503459', 6547, 'Economy', Decimal('16100.00')),
 ('0005435103799', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503458', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503466', 6547, 'Economy', Decimal('16100.00')),
 ('0005434503478', 6547, 'Economy', Decimal('16100.00')),

In [10]:
df = pd.DataFrame(data)

In [12]:
df.head()

               0      1         2         3
0  0005432159776  30625  Business  42100.00
1  0005435212351  30625  Business  42100.00
2  0005435212386  30625  Business  42100.00
3  0005435212381  30625  Business  42100.00
4  0005432211370  30625  Business  42100.00

In [13]:
col_name = ['ticket_no', 'flight_id', 'fare_conditions', 'amount']

In [14]:
df = pd.DataFrame(data, columns=col_name)

In [15]:
df.head()

       ticket_no  flight_id fare_conditions    amount
0  0005432159776      30625        Business  42100.00
1  0005435212351      30625        Business  42100.00
2  0005435212386      30625        Business  42100.00
3  0005435212381      30625        Business  42100.00
4  0005432211370      30625        Business  42100.00

###  DVD RENTAL

In [16]:
conn = pg2.connect(host='localhost', port=5432, dbname='dvdrental', user='postgres', password='palmeiras1914')

In [17]:
cur = conn.cursor()

In [18]:
cur.execute('select * from actor')

In [19]:
conn.commit()

In [20]:
data = cur.fetchall()

In [21]:
colnames = [desc.name for desc in cur.description]

In [22]:
colnames

['actor_id', 'first_name', 'last_name', 'last_update']

In [23]:
cur.close()
conn.close()

In [26]:
cur.description

(Column(name='actor_id', type_code=23),
 Column(name='first_name', type_code=1043),
 Column(name='last_name', type_code=1043),
 Column(name='last_update', type_code=1114))

In [27]:
df = pd.DataFrame(data, columns=colnames)
df.head()

   actor_id first_name     last_name             last_update
0         1   Penelope       Guiness 2013-05-26 14:47:57.620
1         2       Nick      Wahlberg 2013-05-26 14:47:57.620
2         3         Ed         Chase 2013-05-26 14:47:57.620
3         4   Jennifer         Davis 2013-05-26 14:47:57.620
4         5     Johnny  Lollobrigida 2013-05-26 14:47:57.620